language: objective-c
osx_image: xcode10.2
before_install:
- bundle install
- brew outdated carthage || brew upgrade carthage
script:
- .travis/build.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false